# Generated by Django 5.2.5 on 2025-08-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='folder_color',
            field=models.CharField(choices=[('#B7B1F2', 'Primary Purple'), ('#BFECFF', 'Secondary Blue'), ('#FFE0EF', 'Accent Pink'), ('#C1CFA1', 'Success Green'), ('#F0A04B', 'Warning Orange')], default='#B7B1F2', max_length=7),
        ),
        migrations.AddField(
            model_name='course',
            name='room_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
