# Generated by Django 5.2.5 on 2025-08-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_image'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classschedule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='color',
            field=models.CharField(choices=[('#3ED0AE', 'Mint'), ('#127A43', 'Green'), ('#191A2B', 'Dark'), ('#FFCC00', 'Amber'), ('#FF6B6B', 'Coral')], default='#3ED0AE', max_length=7),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='room_location',
            field=models.CharField(default='TBA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classschedule',
            name='title',
            field=models.CharField(default='Untitled Class', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='start_time',
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedule.classschedule')),
            ],
            options={
                'ordering': ['order', 'start_time'],
                'unique_together': {('schedule', 'day_of_week', 'start_time')},
            },
        ),
    ]
