# Generated by Django 5.2.5 on 2025-08-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_classschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='color',
            field=models.CharField(choices=[('#B7B1F2', 'Primary Purple'), ('#BFECFF', 'Secondary Blue'), ('#FFE0EF', 'Accent Pink'), ('#C1CFA1', 'Success Green'), ('#F0A04B', 'Warning Orange')], default='#3ED0AE', max_length=7),
        ),
    ]
